# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install-dev
    - name: Lint
      run: |
        make lint
    - name: Install xtb
      run: |
        sudo apt-get install xtb
    - name: Tests
      run: |
        make test
  test-conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.13'
    - name: Conda install
      shell: bash -el {0}
      run: |
        conda config --add channels conda-forge
        conda install conda-build
        conda install xtb
        conda install veloxchem -c veloxchem
        conda develop .[dev]
    - name: Tests
      shell: bash -el {0}
      run: |
        make install-dev
        make test